# Generated by Django 2.2.1 on 2019-05-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=50, unique=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Storage')),
            ],
        ),
    ]
