# Generated by Django 2.2.1 on 2019-05-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
