# Generated by Django 2.2.1 on 2019-05-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='SKU')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('imei', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='IMEI')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Model')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Storage')),
            ],
        ),
    ]
